name: Publish on Modrinth

on:
  push:
    tags: [ 'v*' ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle and publish on Modrinth
        run: ./gradlew publish
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
